// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mngqhqwvpfmcxwfkqczx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZ3FocXd2cGZtY3h3ZmtxY3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzE5NzMsImV4cCI6MjA2NjgwNzk3M30.88fj_T1zCOZwwICYpb2_8Lq7TLmKPjFD20jgBQ9pnMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});